<?php

use App\Comic;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ComicSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    // for ($i = 1; $i <= 50; $i++) {
    //     $user = rand(1, 2);

    //     factory(Comic::class)->create([
    //         'user_id' => $user,
    //         'created_at' => date('2022-06-23'),
    //     ]);
    // }
    //☝☝ un-comment above if you need to use the factory for testing purposes
    //otherwise, make the data from your google keep below 👇👇

    $date_start = date('2022-06-23'); //YYYY/MM/DD
    $user_id = 1;

    $comics = [
      [
        'user_id' => $user_id,
        'title' => 'SSS-Class Suicide Hunter',
        'url_id' => 1,
        'slug' => 'sss-class-suicide-hunter',
        'chapter' => 80,
        'reading_status' => 'Stacked',
        'note' => '["never read in alphascans, grammar\'s fucked"]',
        'rating' => 4.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Return of the Frozen Player',
        'url_id' => 1,
        'slug' => 'return-of-the-frozen-player-manhwa',
        'chapter' => 50,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Dungeon Reset',
        'url_id' => 1,
        'slug' => 'dungeon-reset',
        'chapter' => 129,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The S-Classes That I Raised',
        'url_id' => 1,
        'slug' => 'the-s-classes-that-i-raised',
        'chapter' => 43,
        'reading_status' => 'Stacked',
        'note' => '["never read in asurascans, grammar\'s fucked"]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Nano Machine',
        'url_id' => 1,
        'slug' => 'nano-machine',
        'chapter' => 113,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Is this Hunter for Real?',
        'url_id' => 1,
        'slug' => 'is-this-hunter-for-real',
        'chapter' => 30,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Return To Player',
        'url_id' => 1,
        'slug' => 'return-to-player',
        'chapter' => 81,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.8,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'God of Blackfield',
        'url_id' => 1,
        'slug' => 'god-of-blackfield',
        'chapter' => 134,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 4.7,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Volcanic Age',
        'url_id' => 1,
        'slug' => 'volcanic-age',
        'chapter' => 209,
        'reading_status' => 'Reading',
        'note' => '["luminous scan\'s is fucked, never try to read it there again"]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Surviving in an Action Manhwa',
        'url_id' => 1,
        'slug' => 'surviving-in-an-action-manhwa',
        'chapter' => 20,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 4.1,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Swordmaster\'s Youngest Son - Manhwa',
        'url_id' => 1,
        'slug' => 'swordmasters-youngest-son-manhwa',
        'chapter' => 28,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 4.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Overgeared',
        'url_id' => 1,
        'slug' => 'overgeared',
        'chapter' => 133,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Leveling With The Gods',
        'url_id' => 1,
        'slug' => 'leveling-with-the-gods-manhwa',
        'chapter' => 58,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Dungeons & Artifacts',
        'url_id' => 1,
        'slug' => 'dungeons-and-artifacts',
        'chapter' => 77,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.6,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Tutorial is Too Hard',
        'url_id' => 1,
        'slug' => 'the-tutorial-is-too-hard-manhwa',
        'chapter' => 69,
        'reading_status' => 'Reading',
        'note' => '["confusing af, keeps jumping from actual present to flashbacks with little to no notice smh"]',
        'rating' => 4.8,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Great Mage that Returned after 4000 Years',
        'url_id' => 1,
        'slug' => 'the-great-mage-that-returned-after-4000-years',
        'chapter' => 133,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.1,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Challenger',
        'url_id' => 1,
        'slug' => 'the-challenger',
        'chapter' => 39,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Archmage Streamer',
        'url_id' => 1,
        'slug' => 'archmage-streamer',
        'chapter' => 43,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.7,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Hero Returns',
        'url_id' => 1,
        'slug' => 'the-hero-returns',
        'chapter' => 35,
        'reading_status' => 'Reading',
        'note' => '["ugh","consider dropping lmao"]',
        'rating' => 3.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Arcane Sniper',
        'url_id' => 1,
        'slug' => 'arcane-sniper',
        'chapter' => 79,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.7,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Seoul Station Druid',
        'url_id' => 1,
        'slug' => 'seoul-station-druid',
        'chapter' => 60,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Player from Today Onwards',
        'url_id' => 1,
        'slug' => 'player-from-today-onwards',
        'chapter' => 46,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 4.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Foreigner on the Periphery',
        'url_id' => 1,
        'slug' => 'foreigner-on-the-periphery',
        'chapter' => 13,
        'reading_status' => 'Stacked',
        'note' => '["stack, ends with cliffhanger"]',
        'rating' => 4.8,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Regressor Instruction Manual',
        'url_id' => 1,
        'slug' => 'regressor-instruction-manual',
        'chapter' => 23,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Dungeon House',
        'url_id' => 1,
        'slug' => 'dungeon-house',
        'chapter' => 24,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Healing Priest of the Sun',
        'url_id' => 1,
        'slug' => 'the-healing-priest-of-the-sun',
        'chapter' => 32,
        'reading_status' => 'Reading',
        'note' => '["lol boring"]',
        'rating' => 3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I Became the Male Lead\'s Adopted Daughter',
        'url_id' => 2,
        'slug' => '91489',
        'chapter' => 51,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Touch My Little Brother and You\'re Dead [Official]',
        'url_id' => 2,
        'slug' => '90543',
        'chapter' => 51,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Chitra',
        'url_id' => 2,
        'slug' => '77717',
        'chapter' => 138,
        'reading_status' => 'Stacked',
        'note' => '["stack since every chapter is short"]',
        'rating' => 4.8,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I\'ll Just Live on as a Villainess',
        'url_id' => 2,
        'slug' => '84970',
        'chapter' => 38,
        'reading_status' => 'Stacked',
        'note' => '["bato.to/series/92998/ (official) > check this also if there\'s updates"]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I Have No Health',
        'url_id' => 2,
        'slug' => '90754',
        'chapter' => 41,
        'reading_status' => 'Stacked',
        'note' => '["stack since every end is cliffhanger"]',
        'rating' => 4.7,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Viridescent Crown (Salty Scans Version)',
        'url_id' => 2,
        'slug' => '95971',
        'chapter' => 71,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Another Typical Fantasy Romance',
        'url_id' => 2,
        'slug' => '96753',
        'chapter' => 42,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Lady Chef Royale',
        'url_id' => 2,
        'slug' => '80362',
        'chapter' => 53,
        'reading_status' => 'Reading',
        'note' => '["(chapter 49)season 2 almost made me dropped this because of personality change of fl smh"]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Legendary Beasts Animal Hospital (Official)',
        'url_id' => 2,
        'slug' => '91940',
        'chapter' => 44,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.7,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I Became the Villain\'s Contract Family [Salty witches co.]',
        'url_id' => 2,
        'slug' => '97884',
        'chapter' => 30,
        'reading_status' => 'Stacked',
        'note' => '["stack since every chapter is short"]',
        'rating' => 4.4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I Became the Wife of the Monstrous Crown Prince',
        'url_id' => 2,
        'slug' => '85907',
        'chapter' => 53,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Say Ah, the Golden Spoon Is Entering (Princess Alliance)',
        'url_id' => 2,
        'slug' => '88147',
        'chapter' => 41,
        'reading_status' => 'Reading',
        'note' => '["also princess alliance dropped it, sadge"]',
        'rating' => 3.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'How to Be a Dark Hero\'s Daughter',
        'url_id' => 2,
        'slug' => '90350',
        'chapter' => 41,
        'reading_status' => 'Stacked',
        'note' => '["stack since every chapter is short"]',
        'rating' => 4.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'My Family is Obsessed with Me',
        'url_id' => 2,
        'slug' => '97568',
        'chapter' => 17,
        'reading_status' => 'Stacked',
        'note' => '["stack since every chapter is short"]',
        'rating' => 4.6,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Éminence Grise Female Lead Is Trying to Make Me Her Stepmom (Princess Alliance)',
        'url_id' => 2,
        'slug' => '85153',
        'chapter' => 23,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 3.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Villainess\'s Days Are Numbered! (Official)',
        'url_id' => 2,
        'slug' => '94610',
        'chapter' => 31,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'A Wicked Tale of Cinderella\'s Stepmom',
        'url_id' => 2,
        'slug' => '81532',
        'chapter' => 77,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.8,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I\'m Worried that My Brother is Too Gentle',
        'url_id' => 2,
        'slug' => '101103',
        'chapter' => 30,
        'reading_status' => 'Reading',
        'note' => '["bato.to/series/94717 (sugar babies are not uploading anymore)"]',
        'rating' => 4.2,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'A Red Knight Does Not Blindly Follow Money',
        'url_id' => 2,
        'slug' => '88091',
        'chapter' => 28,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Youngest Princess',
        'url_id' => 2,
        'slug' => '79488',
        'chapter' => 103,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Evil Lady\'s Hero',
        'url_id' => 2,
        'slug' => '80052',
        'chapter' => 88,
        'reading_status' => 'Reading',
        'note' => '["Waiting for after end specials"]',
        'rating' => 4.7,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Beware the Villainess! (Official)',
        'url_id' => 2,
        'slug' => '83606',
        'chapter' => 93,
        'reading_status' => 'Reading',
        'note' => '["Waiting for after end specials"]',
        'rating' => 4.8,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'A Single Round at Romance is Enough! (Official)',
        'url_id' => 2,
        'slug' => '100364',
        'chapter' => 20,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.1,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Father, I Don\'t Want this Marriage',
        'url_id' => 2,
        'slug' => '83381',
        'chapter' => 33,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 3.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'As You Wish, Prince',
        'url_id' => 2,
        'slug' => '74247',
        'chapter' => 23,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 3.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I Became the Hero\'s Mom',
        'url_id' => 2,
        'slug' => '83866',
        'chapter' => 42,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Tyrant\'s Guardian is an Evil Witch',
        'url_id' => 2,
        'slug' => '83151',
        'chapter' => 28,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 3.8,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Lady Wants to Rest [Bored Corona Kids version]',
        'url_id' => 2,
        'slug' => '84538',
        'chapter' => 44,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Why She Lives as a Villainess',
        'url_id' => 2,
        'slug' => '88548',
        'chapter' => 31,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Villainous Princess Wants to Live in a Cookie House',
        'url_id' => 2,
        'slug' => '87557',
        'chapter' => 43,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 3.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Precious Sister of the Villainous Grand Duke',
        'url_id' => 2,
        'slug' => '84622',
        'chapter' => 50,
        'reading_status' => 'Reading',
        'note' => '["ugh","she\'s playing herself smh what a moron","typical isekai bullshit"]',
        'rating' => 3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Today the Villainess Has Fun Again',
        'url_id' => 2,
        'slug' => '91930',
        'chapter' => 31,
        'reading_status' => 'Reading',
        'note' => '["ugh","the ml is the fucking kid smh cringe","webtoon for women with shotacon fetish ew"]',
        'rating' => 3.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Wicked Little Princess',
        'url_id' => 2,
        'slug' => '95981',
        'chapter' => 35,
        'reading_status' => 'Reading',
        'note' => '["she became unnecessarily arrogant"]',
        'rating' => 4.1,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Lady\'s Butler',
        'url_id' => 2,
        'slug' => '79916',
        'chapter' => 46,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => null,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Empress? Empress!',
        'url_id' => 2,
        'slug' => '78242',
        'chapter' => 70,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 3.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'You Can\'t Change a Person! (Official)',
        'url_id' => 2,
        'slug' => '86968',
        'chapter' => 23,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 3.7,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I Choose the Emperor Ending',
        'url_id' => 2,
        'slug' => '76421',
        'chapter' => 76,
        'reading_status' => 'On Hold',
        'note' => '[]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Lady Tames the Swordmaster',
        'url_id' => 2,
        'slug' => '87689',
        'chapter' => 22,
        'reading_status' => 'Plan To Read',
        'note' => '[]',
        'rating' => 3.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Villain To The Rescue!',
        'url_id' => 2,
        'slug' => '87597',
        'chapter' => 11,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 3.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Spirit Farmer',
        'url_id' => 3,
        'slug' => 'spirit-farmer',
        'chapter' => 99,
        'reading_status' => 'Stacked',
        'note' => '["stack because it\'s not enough"]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'My Daughter is the Final Boss',
        'url_id' => 3,
        'slug' => 'my-daughter-is-the-final-boss',
        'chapter' => 34,
        'reading_status' => 'Stacked',
        'note' => '["stack because it\'s not enough"]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Constellation that Returned from Hell',
        'url_id' => 3,
        'slug' => 'the-constellation-that-returned-from-hell',
        'chapter' => 86,
        'reading_status' => 'Stacked',
        'note' => '["stack because it\'s short af"]',
        'rating' => 4.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Reincarnation of the Suicidal Battle God',
        'url_id' => 3,
        'slug' => 'reincarnation-of-the-suicidal-battle-god',
        'chapter' => 56,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Death Is the Only Ending for the Villainess',
        'url_id' => 3,
        'slug' => 'death-is-the-only-ending-for-the-villainess',
        'chapter' => 90,
        'reading_status' => 'Stacked',
        'note' => '["stack because it\'s not enough"]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Solo Max-Level Newbie',
        'url_id' => 3,
        'slug' => 'solo-max-level-newbie',
        'chapter' => 56,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Tutorial Tower of the Advanced Player',
        'url_id' => 3,
        'slug' => 'the-tutorial-tower-of-the-advanced-player',
        'chapter' => 121,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Worn and Torn Newbie',
        'url_id' => 3,
        'slug' => 'worn-and-torn-newbie',
        'chapter' => 100,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Max Level Hero has Returned!',
        'url_id' => 3,
        'slug' => 'the-max-level-hero-has-returned',
        'chapter' => 93,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.8,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Return of the Mount Hua Sect',
        'url_id' => 3,
        'slug' => 'return-of-the-mount-hua-sect',
        'chapter' => 72,
        'reading_status' => 'Stacked',
        'note' => '["stack because it\'s not enough"]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Seoul Station Necromancer',
        'url_id' => 3,
        'slug' => 'seoul-stations-necromancer',
        'chapter' => 52,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.8,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'How To Live As a Villain',
        'url_id' => 3,
        'slug' => 'how-to-live-as-a-villain',
        'chapter' => 47,
        'reading_status' => 'On Hold',
        'note' => '[]',
        'rating' => 4.1,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Murim Login',
        'url_id' => 3,
        'slug' => 'murim-login',
        'chapter' => 118,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Dark Magician Transmigrates After 66666 Years',
        'url_id' => 3,
        'slug' => 'the-dark-magician-transmigrates-after-66666-years',
        'chapter' => 58,
        'reading_status' => 'Stacked',
        'note' => '["stack because author likes to force things smh"]',
        'rating' => 4.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Return of the Crazy Demon',
        'url_id' => 3,
        'slug' => 'the-return-of-the-crazy-demon',
        'chapter' => 53,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Return of the Disaster-Class Hero',
        'url_id' => 3,
        'slug' => 'return-of-the-disaster-class-hero',
        'chapter' => 43,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Duke Pendragon',
        'url_id' => 3,
        'slug' => 'duke-pendragon',
        'chapter' => 44,
        'reading_status' => 'Stacked',
        'note' => '["stack"]',
        'rating' => 4.8,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Legendary Youngest Son of the Marquis House (Manhwa)',
        'url_id' => 3,
        'slug' => 'legendary-youngest-son-of-the-marquis-house-manhwa',
        'chapter' => 37,
        'reading_status' => 'Stacked',
        'note' => '["stack because it\'s short as shit"]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Doctor\'s Rebirth',
        'url_id' => 3,
        'slug' => 'doctors-rebirth',
        'chapter' => 90,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.6,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Reformation of the Deadbeat Noble',
        'url_id' => 3,
        'slug' => 'reformation-of-the-deadbeat-noble',
        'chapter' => 56,
        'reading_status' => 'Stacked',
        'note' => '["stack because  it ends with shit ass cliff hanger"]',
        'rating' => 4.7,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'To Hell With Being A Saint, I\'m A Doctor',
        'url_id' => 3,
        'slug' => 'to-hell-with-being-a-saint-im-a-doctor',
        'chapter' => 26,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Talent-Swallowing Magician',
        'url_id' => 3,
        'slug' => 'talent-swallowing-magician',
        'chapter' => 38,
        'reading_status' => 'Stacked',
        'note' => '["stack because it\'s short as shit"]',
        'rating' => 4.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Lord\'s Coins Aren\'t Decreasing?!',
        'url_id' => 3,
        'slug' => 'the-lords-coins-arent-decreasing',
        'chapter' => 71,
        'reading_status' => 'Stacked',
        'note' => '["stack because it ends with shit ass cliff hanger"]',
        'rating' => 4.7,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Newbie is Too Strong',
        'url_id' => 3,
        'slug' => 'the-newbie-is-too-strong',
        'chapter' => 24,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 4.5,
        'created_at' => date('2022-06-27'),
      ],
      [
        'user_id' => $user_id,
        'title' => 'I Reincarnated As The Crazed Heir',
        'url_id' => 3,
        'slug' => 'i-reincarnated-as-the-crazed-heir',
        'chapter' => 54,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Street Restaurant of a Returned Hero',
        'url_id' => 3,
        'slug' => 'street-restaurant-of-a-returned-hero',
        'chapter' => 28,
        'reading_status' => 'On Hold',
        'note' => '[]',
        'rating' => 3.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Worthless Regression',
        'url_id' => 3,
        'slug' => 'worthless-regression',
        'chapter' => 22,
        'reading_status' => 'On Hold',
        'note' => '["ugh"]',
        'rating' => 3.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Return of the 8th Class Magician',
        'url_id' => 3,
        'slug' => 'return-of-the-8th-class-magician',
        'chapter' => 62,
        'reading_status' => 'Stacked',
        'note' => '["kinda became a meh? idk"]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Return Of The Shattered Constellation',
        'url_id' => 3,
        'slug' => 'return-of-the-shattered-constellation',
        'chapter' => 37,
        'reading_status' => 'Reading',
        'note' => '["nice art, not story"]',
        'rating' => 3.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Taming Master',
        'url_id' => 3,
        'slug' => '1649969363-taming-master',
        'chapter' => 68,
        'reading_status' => 'On Hold',
        'note' => '[]',
        'rating' => 2.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Path of the Shaman',
        'url_id' => 3,
        'slug' => 'path-of-the-shaman',
        'chapter' => 41,
        'reading_status' => 'On Hold',
        'note' => '[]',
        'rating' => null,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Maxed Out Leveling',
        'url_id' => 3,
        'slug' => 'maxed-out-leveling',
        'chapter' => 51,
        'reading_status' => 'On Hold',
        'note' => '["beware: cliffhanging galore"]',
        'rating' => 3.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Heavenly Demon Instructor',
        'url_id' => 3,
        'slug' => 'heavenly-demon-instructor',
        'chapter' => 40,
        'reading_status' => 'On Hold',
        'note' => '["cliffhanging piece of shit smh","ugh","consider dropping, not good to mental health tbh"]',
        'rating' => 2.6,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'SSS-Class Gacha Hunter',
        'url_id' => 3,
        'slug' => 'sss-class-gacha-hunter',
        'chapter' => 14,
        'reading_status' => 'On Hold',
        'note' => '[]',
        'rating' => 3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Sleeping Ranker',
        'url_id' => 3,
        'slug' => 'sleeping-ranker',
        'chapter' => 36,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => date('2022-07-04'),
      ],
      [
        'user_id' => $user_id,
        'title' => 'Omniscient Reader\'s Viewpoint',
        'url_id' => 4,
        'slug' => 'omniscient-readers-viewpoint',
        'chapter' => 115,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Heavenly Demon Cultivation Simulation',
        'url_id' => 4,
        'slug' => 'heavenly-demon-cultivation-simulation',
        'chapter' => 45,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Villainess is a Marionette',
        'url_id' => 4,
        'slug' => 'the-villainess-is-a-marionette',
        'chapter' => 59,
        'reading_status' => 'Reading',
        'note' => '["DMCA\'ed"]',
        'rating' => 4.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Solo Necromancy',
        'url_id' => 4,
        'slug' => 'solo-necromancy',
        'chapter' => 48,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 4.7,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Reincarnation of the Murim Clan\'s Former Ranker',
        'url_id' => 4,
        'slug' => 'reincarnation-of-the-murim-clans-former-ranker',
        'chapter' => 50,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'A Returner\'s Magic Should Be Special',
        'url_id' => 4,
        'slug' => 'a-returners-magic-should-be-special',
        'chapter' => 195,
        'reading_status' => 'Reading',
        'note' => '["DMCA\'ed","flamesccans dropped it because of dmca, picked up by luminous"]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'A Stepmother\'s Märchen',
        'url_id' => 2,
        'slug' => '83291',
        'chapter' => 69,
        'reading_status' => 'Reading',
        'note' => '["flamescans dropped it because of official tls"]',
        'rating' => 4.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'FFF-Class Trash Hero',
        'url_id' => 5,
        'slug' => 'fff-class-trash-hero',
        'chapter' => 110,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Trash of the Count\'s Family',
        'url_id' => 3,
        'slug' => 'trash-of-the-counts-family',
        'chapter' => 90,
        'reading_status' => 'Stacked',
        'note' => '["stack because it ends with shit ass cliff hanger and also short as shit",
                    "collaboration of alphascans and asurascans so check the alphascans if asura ain\'t uploading"]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Mercenary Enrollment',
        'url_id' => 1,
        'slug' => 'mercenary-enrollment',
        'chapter' => 93,
        'reading_status' => 'Stacked',
        'note' => '["if not stacked, read in luminousscans because they upload fast but grammar is ight"]',
        'rating' => 4.8,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'MEMORIZE',
        'url_id' => 5,
        'slug' => 'memorize',
        'chapter' => 101,
        'reading_status' => 'Stacked',
        'note' => '["stack because it ends with shit ass cliff hanger and also short as shit"]',
        'rating' => 4.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'My Dad Is Too Strong',
        'url_id' => 5,
        'slug' => 'my-dad-is-so-powerful',
        'chapter' => 91,
        'reading_status' => 'Stacked',
        'note' => '["stack just because"]',
        'rating' => 4.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Live',
        'url_id' => 3,
        'slug' => 'the-live',
        'chapter' => 92,
        'reading_status' => 'On Hold',
        'note' => '["nice art and story but shit action and script considering that\'s somewhat the hightlight too smh",
                    "consider dropping"]',
        'rating' => 1.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Book Eater',
        'url_id' => 9,
        'slug' => 'book-eater',
        'chapter' => 34,
        'reading_status' => 'On Hold',
        'note' => '[]',
        'rating' => 3.6,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I\'m Only A Stepmother, But My Daughter Is Just So Cute! ',
        'url_id' => 6,
        'slug' => 'im-the-stepmother-but-my-daughter-is-too-cute',
        'chapter' => 65,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.6,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I\'m A Martial Art Villainess But I\'m The Strongest!',
        'url_id' => 6,
        'slug' => 'im-a-martial-art-villainess-but-im-the-strongest',
        'chapter' => 37,
        'reading_status' => 'Plan To Read',
        'note' => '[]',
        'rating' => null,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I Tamed a Tyrant and Ran Away',
        'url_id' => 6,
        'slug' => 'i-tamed-a-tyrant-and-ran-away',
        'chapter' => 41,
        'reading_status' => 'Plan To Read',
        'note' => '[]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Not Just Anybody Can Become a Villainess',
        'url_id' => 6,
        'slug' => 'not-just-anybody-can-become-a-villainess',
        'chapter' => 25,
        'reading_status' => 'Plan To Read',
        'note' => '[]',
        'rating' => null,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Reader',
        'url_id' => 7,
        'slug' => 'reader',
        'chapter' => 155,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'A.i Doctor',
        'url_id' => 7,
        'slug' => 'a-i-doctor',
        'chapter' => 66,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Trapped in a Webnovel as a Good for Nothing',
        'url_id' => 8,
        'slug' => '1645401723-trapped-in-a-webnovel-as-a-good-for-nothing',
        'chapter' => 102,
        'reading_status' => 'Stacked',
        'note' => '["asurascans x alphascans collab so if this url still has no updates, check asura"]',
        'rating' => 4.6,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Ranker\'s Return (Remake)',
        'url_id' => 1,
        'slug' => 'rankers-return',
        'chapter' => 65,
        'reading_status' => 'Reading',
        'note' => '["alphascans tl is shit because they\'re not consistent with character names smh"]',
        'rating' => 4.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Kill The Hero',
        'url_id' => 8,
        'slug' => 'kill-the-hero',
        'chapter' => 101,
        'reading_status' => 'Reading',
        'note' => '["alphascans tl is bearable but if you want legit good shit, check reaperscans"]',
        'rating' => 4.4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Reincarnated as a Legendary Surgeon',
        'url_id' => 8,
        'slug' => 'i-reincarnated-as-a-legendary-surgeon',
        'chapter' => 42,
        'reading_status' => 'Stacked',
        'note' => '["stack because it\'s cliff hanger and SHORT AS SHIT"]',
        'rating' => 4.6,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Immortal Emperor Luo Wuji Has Returned',
        'url_id' => 8,
        'slug' => 'the-immortal-emperor-luo-wuji-has-returned',
        'chapter' => 138,
        'reading_status' => 'Stacked',
        'note' => '["stack because it\'s cliff hanger and short as shit"]',
        'rating' => 4.1,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Descent of the Demonic Master',
        'url_id' => 8,
        'slug' => '1644105722-the-descent-of-the-demonic-master',
        'chapter' => 142,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 3.9,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Gamer',
        'url_id' => 9,
        'slug' => 'the-gamer',
        'chapter' => 431,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Scholarly Reincarnation',
        'url_id' => 9,
        'slug' => 'the-scholarly-reincarnation',
        'chapter' => 199,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I Will Make an Attempt to Change the Genre',
        'url_id' => 10,
        'slug' => 'time-to-change-the-genre',
        'chapter' => 50,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Leveling Up, by Only Eating!',
        'url_id' => 11,
        'slug' => 'i-level-up-by-eating',
        'chapter' => 105,
        'reading_status' => 'Reading',
        'note' => '["pmscans/rackusreader is fucking shit but they\'re the official english tl now smh"]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Tales of Demons and Gods',
        'url_id' => 12,
        'slug' => 'tales-of-demons-and-gods',
        'chapter' => 387,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Second Life Ranker',
        'url_id' => 13,
        'slug' => 'second-life-ranker',
        'chapter' => 124,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Forced to Become the Villainous Son-in-law',
        'url_id' => 14,
        'slug' => '18032',
        'chapter' => 92,
        'reading_status' => 'Plan To Read',
        'note' => '[]',
        'rating' => null,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Goblin Slayer',
        'url_id' => 14,
        'slug' => '15987',
        'chapter' => 72,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Goblin Slayer: Side Story Year One',
        'url_id' => 14,
        'slug' => '16151',
        'chapter' => 72,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I\'m Just an Immortal',
        'url_id' => 15,
        'slug' => 'im-just-an-immortal',
        'chapter' => 58,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => null,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The Overachiever\'s Black Tech System Comics',
        'url_id' => 16,
        'slug' => 'the-overachievers-black-tech-system-comics',
        'chapter' => 62,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'The King\'s Avatar (reboot)',
        'url_id' => 17,
        'slug' => 'the-king-s-avatar-reboot',
        'chapter' => 86,
        'reading_status' => 'Stacked',
        'note' => '[]',
        'rating' => 5,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Extraordinary Son-In-Law',
        'url_id' => 18,
        'slug' => 'we923906',
        'chapter' => 62,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.1,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Time Stop Brave',
        'url_id' => 19,
        'slug' => 'hl984820',
        'chapter' => 21,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 3.8,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Gokufuri Kyohi Shite Tesaguri Sutato! Toku-Ka Shinai Hira, Nakama To Wakarete Tabi Ni Deru',
        'url_id' => 19,
        'slug' => 'ku987955',
        'chapter' => 28,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4.3,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'Little Girl X Scoop X Evil Eye',
        'url_id' => 19,
        'slug' => 'ik985467',
        'chapter' => 13,
        'reading_status' => 'Reading',
        'note' => '[]',
        'rating' => 4,
        'created_at' => $date_start,
      ],
      [
        'user_id' => $user_id,
        'title' => 'I Became a Renowned Family\'s Sword Prodigy',
        'url_id' => 3,
        'slug' => 'i-became-a-renowned-familys-sword-prodigy',
        'chapter' => 17,
        'reading_status' => 'Reading',
        'note' => '["it\'s just a revenge plot so don\'t expect anything"]',
        'rating' => 4.1,
        'created_at' => date('2022-07-06'),
      ],
    ];

    // if rating == null means i forgot everything about it lmao
    foreach ($comics as $comic) {
      Comic::create($comic);
    }
  }
}
